export const USA_MAP_DATA = [
  { state: "Alabama", id: "AL", guessed: false },
  { state: "Alaska", id: "AK", guessed: false },
  { state: "Arizona", id: "AZ", guessed: false },
  { state: "Arkansas", id: "AR", guessed: false },
  { state: "California", id: "CA", guessed: false },
  { state: "Colorado", id: "CO", guessed: false },
  { state: "Connecticut", id: "CT", guessed: false },
  { state: "Delaware", id: "DE", guessed: false },
  { state: "Florida", id: "FL", guessed: false },
  { state: "Georgia", id: "GA", guessed: false },
  { state: "Hawaii", id: "HI", guessed: false },
  { state: "Idaho", id: "ID", guessed: false },
  { state: "Illinois", id: "IL", guessed: false },
  { state: "Indiana", id: "IN", guessed: false },
  { state: "Iowa", id: "IA", guessed: false },
  { state: "Kansas", id: "KS", guessed: false },
  { state: "Kentucky", id: "KY", guessed: false },
  { state: "Louisiana", id: "LA", guessed: false },
  { state: "Maine", id: "ME", guessed: false },
  { state: "Maryland", id: "MD", guessed: false },
  { state: "Massachusetts", id: "MA", guessed: false },
  { state: "Michigan", id: "MI", guessed: false },
  { state: "Minnesota", id: "MN", guessed: false },
  { state: "Mississippi", id: "MS", guessed: false },
  { state: "Missouri", id: "MO", guessed: false },
  { state: "Montana", id: "MT", guessed: false },
  { state: "Nebraska", id: "NE", guessed: false },
  { state: "Nevada", id: "NV", guessed: false },
  { state: "New Hampshire", id: "NH", guessed: false },
  { state: "New Jersey", id: "NJ", guessed: false },
  { state: "New Mexico", id: "NM", guessed: false },
  { state: "New York", id: "NY", guessed: false },
  { state: "North Carolina", id: "NC", guessed: false },
  { state: "North Dakota", id: "ND", guessed: false },
  { state: "Ohio", id: "OH", guessed: false },
  { state: "Oklahoma", id: "OK", guessed: false },
  { state: "Oregon", id: "OR", guessed: false },
  { state: "Pennsylvania", id: "PA", guessed: false },
  { state: "Rhode Island", id: "RI", guessed: false },
  { state: "South Carolina", id: "SC", guessed: false },
  { state: "South Dakota", id: "SD", guessed: false },
  { state: "Tennessee", id: "TN", guessed: false },
  { state: "Texas", id: "TX", guessed: false },
  { state: "Utah", id: "UT", guessed: false },
  { state: "Vermont", id: "VT", guessed: false },
  { state: "Virginia", id: "VA", guessed: false },
  { state: "Washington", id: "WA", guessed: false },
  { state: "West Virginia", id: "WV", guessed: false },
  { state: "Wisconsin", id: "WI", guessed: false },
  { state: "Wyoming", id: "WY", guessed: false }
]
